<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Himanshusingh01" name="TEST" tests="10" failures="9" timestamp="1 Nov 2019 10:07:07 GMT" time="30.001" errors="0">
  <testcase name="checkGET" time="2.336" classname="com.RestAssured.testCases.GET_1_Test"/>
  <testcase name="checkGETbyID" time="0.001" classname="com.RestAssured.testCases.GET_2_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.GET_2_Test.checkGETbyID(GET_2_Test.java:27)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkGETbyID -->
  <testcase name="checkPOST_1" time="0.003" classname="com.RestAssured.testCases.POST_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.POST_Test.checkPOST_1(POST_Test.java:30)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkPOST_1 -->
  <testcase name="checkPOST_2" time="0.004" classname="com.RestAssured.testCases.POST_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.POST_Test.checkPOST_2(POST_Test.java:59)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkPOST_2 -->
  <testcase name="Delete_1" time="0.001" classname="com.RestAssured.testCases.DELETE_1_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.DELETE_1_Test.Delete_1(DELETE_1_Test.java:30)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Delete_1 -->
  <testcase name="Delete_2" time="0.002" classname="com.RestAssured.testCases.DELETE_2_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.DELETE_2_Test.Delete_2(DELETE_2_Test.java:30)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Delete_2 -->
  <testcase name="put_1" time="0.005" classname="com.RestAssured.testCases.PUT_1_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.PUT_1_Test.put_1(PUT_1_Test.java:34)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- put_1 -->
  <testcase name="put_2" time="0.001" classname="com.RestAssured.testCases.PUT_2_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.PUT_2_Test.put_2(PUT_2_Test.java:32)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- put_2 -->
  <testcase name="patch_1" time="0.0" classname="com.RestAssured.testCases.PATCH_1_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.PATCH_1_Test.patch_1(PATCH_1_Test.java:32)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- patch_1 -->
  <testcase name="patch_2" time="0.001" classname="com.RestAssured.testCases.PATCH_2_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.PATCH_2_Test.patch_2(PATCH_2_Test.java:32)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- patch_2 -->
</testsuite> <!-- TEST -->
